#我有啥
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-live-mysql-claim
spec:
  storageClassName: candy
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"