// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"goFoundation/webook/internal/repository"
	"goFoundation/webook/internal/repository/cache"
	"goFoundation/webook/internal/repository/dao"
	"goFoundation/webook/internal/service"
	"goFoundation/webook/internal/web"
	"goFoundation/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDb()
	userDaoIF := dao.NewUserService(db)
	usersCacheIF := cache.NewCacheUsers(cmdable)
	userRepositoryIF := repository.NewUserService(userDaoIF, usersCacheIF)
	userServiceIF := service.NewUserService(userRepositoryIF)
	codeCacheIF := cache.NewCacheCode(cmdable)
	codeRepositoryIF := repository.NewRepositoryCode(codeCacheIF)
	smsService := ioc.InitSMSService()
	codeServiceIF := service.NewServiceCode(codeRepositoryIF, smsService)
	userHandler := web.NewUserHandle(userServiceIF, codeServiceIF)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
