// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"goFoundation/webook/interactive/events"
	"goFoundation/webook/interactive/grpc"
	"goFoundation/webook/interactive/ioc"
	"goFoundation/webook/interactive/repository"
	"goFoundation/webook/interactive/repository/cache"
	"goFoundation/webook/interactive/repository/dao"
	"goFoundation/webook/interactive/service"
)

// Injectors from wire.go:

func InitAPP() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	serverGrpc := grpc.NewServerGrpc(interactiveService)
	server := ioc.InitGrpc(serverGrpc)
	client := ioc.InitKafka()
	consumerEvent := events.NewConsumerEvents(client, loggerV1, interactiveRepository)
	v := ioc.NewConsumers(consumerEvent)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var InitWire = wire.NewSet(ioc.InitRedis, ioc.InitDB, ioc.InitLogger, ioc.InitKafka)

var InteractiveWire = wire.NewSet(dao.NewInteractiveDAO, cache.NewInteractiveCache, repository.NewInteractiveRepository, service.NewInteractiveService)
