// Code generated by MockGen. DO NOT EDIT.
// Source: webook/internal/service/oauth2/wechat/types.go

// Package wechatmocks is a generated GoMock package.
package wechatmocks

import (
	context "context"
	domain "goFoundation/webook/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AuthUrl mocks base method.
func (m *MockService) AuthUrl(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUrl", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthUrl indicates an expected call of AuthUrl.
func (mr *MockServiceMockRecorder) AuthUrl(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUrl", reflect.TypeOf((*MockService)(nil).AuthUrl), ctx)
}

// VerifyCode mocks base method.
func (m *MockService) VerifyCode(ctx context.Context, code, state string) (domain.WechatInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, code, state)
	ret0, _ := ret[0].(domain.WechatInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockServiceMockRecorder) VerifyCode(ctx, code, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockService)(nil).VerifyCode), ctx, code, state)
}
